<?xml version="1.0" encoding="utf-8"?><Database Name="test_daniel" Class="DatabaseEntitiesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="ConnectionString" ConnectionString="Data Source=sm-arba-vdev01;Initial Catalog=test_daniel;Persist Security Info=True;User ID=webappuser;Password=w3b@ppuS3R" Provider="System.Data.SqlClient" />
  <Function Name="dbo.AddSpins" Method="AddSpins">
    <Parameter Name="deviceId" Type="System.String" DbType="NChar(25)" />
    <Parameter Name="millis" Type="System.Int32" DbType="Int" />
    <Parameter Name="spins" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
</Database>